    {
      "type": "VŨNG TÀU",
      "geometry": {
        "type": "Point",
        "coordinates": [107.5337732,10.557641]
      },
      "properties": {
        "title": "TRUNG NAM",
        "description": "ấp Thèo Nèo, Xã Bình Châu, Huyện Xuyên Mộc, Tỉnh Bà Rịa - Vũng Tàu",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.816571,10.133135]
      },
      "properties": {
        "title": "PHẠM MINH THÔNG",
        "description": "Tổ 03/ ấp Hòa Thuận, xã Nguyễn Văn Thảnh, huyện Bình Tân, Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.764320,10.157968]
      },
      "properties": {
        "title": "TÂN MINH THÀNH (HẢI HƯƠNG)",
        "description": "Tổ 05/ ấp Tân Lập, xã Tân Thành, huyện Bình Tân, Tỉnh Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.923149,9.964272]
      },
      "properties": {
        "title": "HIỆP THÀNH",
        "description": "Tổ 04, khu 8, thị trấn Trà Ôn, Huyện Trà Ôn, Tỉnh Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.147542,10.067614]
      },
      "properties": {
        "title": "NGUYỄN THỊ HẰNG",
        "description": "Tổ 15, ấp Bình Thành, xã Trung Hiếu, Huyện Vũng Liêm, Tỉnh Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.172495,10.077280]
      },
      "properties": {
        "title": "TRẦN HỚN QUANG",
        "description": "KII, Thị Trấn, Huyện Vũng Liêm, Tỉnh Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.146181,10.068926]
      },
      "properties": {
        "title": "ÚT MÂN",
        "description": "Số 287 ấp Bình Thành, Xã Trung Hiếu, H. Vũng Liêm, T .Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "VĨNH LONG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.836342,10.045014]
      },
      "properties": {
        "title": "HỒNG LIÊN",
        "description": "Khóm Đông Thuận, Phường Đông Thuận, Thị xã Bình Minh, Tỉnh Vĩnh Long",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.239754,9.961620]
      },
      "properties": {
        "title": "KIM RY",
        "description": "Bình Phú, Càng Long, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.098046,9.810004]
      },
      "properties": {
        "title": "MỘC",
        "description": "ấp 1, xă Phong Phú, huyện Cầu Kè, tỉnh Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.055765,9.872581]
      },
      "properties": {
        "title": "ÚT HÒA THUẬN",
        "description": "Khóm 5, Thị Trấn Cầu Kè, Huyện Cầu Kè, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.450824,9.792628]
      },
      "properties": {
        "title": "SÁU MIỀN",
        "description": "147 Đường 3/2, Thị Trấn Cầu Ngang, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.425170,9.753003]
      },
      "properties": {
        "title": "THẦY LỜI",
        "description": "Ấp Bào Mót, Xã Long Sơn, Cầu Ngang, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.343713,9.874335]
      },
      "properties": {
        "title": "MƯỜI TRÃI",
        "description": "Khóm 2, Thị Trấn Châu Thành, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.348714,9.643483]
      },
      "properties": {
        "title": "HÒA HIỆP",
        "description": "Đôn Xuân, Trà Cú, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.187488,9.811713]
      },
      "properties": {
        "title": "TRẦN THỊ YẾN",
        "description": "Khóm 1, TT Cầu Quan, huyện Tiểu Cần, tỉnh Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.265792,9.819939]
      },
      "properties": {
        "title": "VÕ THỊ THẤY",
        "description": "ấp Ngô Văn Kiệt, Xã Tập Ngãi, Huyện Tiểu Cần, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.255206,9.743301]
      },
      "properties": {
        "title": "HỮU PHƯỚC",
        "description": "ấp Chợ, xã Tập Sơn, Huyện Trà Cú, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.338900,9.701683]
      },
      "properties": {
        "title": "THANH MAI",
        "description": "ấp Chợ, Xã Long Hiệp, Huyện Trà Cú , Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.343290,9.936957]
      },
      "properties": {
        "title": "MINH ĐỨC",
        "description": "Số 29C-29D Hùng Vương, khóm 1, Phường 3, Thành phố Trà Vinh, Tỉnh Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TRÀ VINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.497358,9.633118]
      },
      "properties": {
        "title": "BẢY DŨNG",
        "description": "TT. Duyên Hải, thị xã Duyên Hải, Trà Vinh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.971891,10.359087]
      },
      "properties": {
        "title": "LÊ MINH THẮNG",
        "description": "ấp Mỹ Phú, xã Thiện Trí, huyện Cái Bè, Tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.968284,10.505446]
      },
      "properties": {
        "title": "LÊ VĂN PHÚC",
        "description": "Hậu Mỹ Bắc A, huyện Cái Bè, tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.941037,10.358151]
      },
      "properties": {
        "title": "MÃ THÀNH TÍNH",
        "description": "ấp Mỹ Hưng A, xã Mỹ Đức Đông, Huyện Cái Bè, Tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.850931,10.339426]
      },
      "properties": {
        "title": "NGUYỄN KIM BẢY",
        "description": "Xã Tân Hưng, huyện Cái Bè, tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.083362,10.325157]
      },
      "properties": {
        "title": "BÙI MINH TÂM",
        "description": "ấp Hội Nghĩa, xã Hội Xuân, huyện Cai Lậy, tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.171174,10.353540]
      },
      "properties": {
        "title": "HOÀNG DŨNG",
        "description": "ấp Mỹ Hội, xã Mỹ Long, huyện Cai Lậy, tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.179267,10.317005]
      },
      "properties": {
        "title": "HUỲNH CÔNG ĐẠT",
        "description": "ấp Đông Hòa, xã Tam Bình, huyện Cai Lậy, tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.082318,10.398352]
      },
      "properties": {
        "title": "PHƯỚC QUANG",
        "description": "ấp Bình Tịnh, Xã Bình Phú, huyện Cai Lậy, Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.234423,10.405239]
      },
      "properties": {
        "title": "TRẦN VĂN HỒNG",
        "description": "Thửa đất số 4752, ấp Tây, xã Nhị Bình, huyện Châu Thành, Tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.523511,10.354909]
      },
      "properties": {
        "title": "LÊ VĂN THẠCH",
        "description": "ấp Tân Thạnh, Xã Thạnh Nhựt, Huyện Gò Công Tây, Tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.086181,10.414539]
      },
      "properties": {
        "title": "TÂN TIẾN",
        "description": "QL1A, ấp Bình Đức, Bình Phú, Cai Lậy, Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TIỀN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.129462,10.383570]
      },
      "properties": {
        "title": "VÕ VĂN TÁM",
        "description": "ấp phú Hưng, xã Long Khánh, Thị xã Cai Lậy, Tỉnh Tiền Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [105.996865,11.282052]
      },
      "properties": {
        "title": "THÀNH LONG",
        "description": "C24 Tổ 5, ấp Nam Bến Sỏi, xã Thành Long, huyện Châu Thành, Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.0965391,11.2876088]
      },
      "properties": {
        "title": "NGUYỄN TRUNG SÂM",
        "description": "Hiệp Tân, Hoà Thành, Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.403714,11.016593]
      },
      "properties": {
        "title": "NGUYỄN THỊ TUYẾT",
        "description": "ấp Suối Sâu, Xã An Tịnh, Huyện Trảng Bàng, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.394508,11.029899]
      },
      "properties": {
        "title": "TRƯƠNG BÁ KHIÊM",
        "description": "ấp An Thới, xã An Tịnh, huyện Trảng Bàng, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.046616,11.354307]
      },
      "properties": {
        "title": "BÍCH PHƯỢNG",
        "description": "ấp Tua Hai, Xã Đồng Khởi, Huyện Châu Thành, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.164142,11.548941]
      },
      "properties": {
        "title": "CAO PHÁT",
        "description": "Tổ 10, KP1, Thị trấn Tân Châu, Tân Châu, Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.105517,11.107021]
      },
      "properties": {
        "title": "NĂM REN 1",
        "description": "Tổ 8, ấp Long hưng, xã Long Thuận, huyện Bến Cầu, tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.232102, 11.176734]
      },
      "properties": {
        "title": "TRẦN VĂN PHƯỚC",
        "description": "425, Tổ 22, ấp Bến Mương, xã Thạnh Đức, huyện Gò Dầu, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.133691,11.281260]
      },
      "properties": {
        "title": "TRƯƠNG THỊ LIÊN",
        "description": "B2/6, ấp Long Thời, Xã Long Thành Bắc, Huyện Hòa Thành, Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.169308,11.595095]
      },
      "properties": {
        "title": "NGỌC TRÂM",
        "description": "Tổ 1, ấp Hội Thắng, xã Tân Hiệp, Huyện Tân Châu, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.368996,11.165726]
      },
      "properties": {
        "title": "DƯƠNG VĂN TÁM",
        "description": "huyện Trảng Bàng, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.419808,11.113177]
      },
      "properties": {
        "title": "LÊ HỮU YẾN",
        "description": "huyện Trảng Bàng, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.329534,11.037150]
      },
      "properties": {
        "title": "NGUYỄN THỊ KIM CHI",
        "description": "ấp Hòa Hưng, Xã An Hòa, Huyện Trảng Bàng, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.361799,11.078307]
      },
      "properties": {
        "title": "NGUYỄN VĂN ĐÊN",
        "description": "huyện Trảng Bàng, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "TÂY NINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.137596,11.341148]
      },
      "properties": {
        "title": "PHẠM THÀNH HUYÊN",
        "description": "Thành phố Tây Ninh, Tỉnh Tây Ninh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SƠN LA",
      "geometry": {
        "type": "Point",
        "coordinates": [104.095539,21.2033374]
      },
      "properties": {
        "title": "ĐẶNG VĂN LÂN",
        "description": "Tiểu Khu 19, T.T Hát Lót, Huyện Mai Sơn, Sơn La",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.923046,9.629491]
      },
      "properties": {
        "title": "HẢI YẾN",
        "description": "Số 215, ấp Bưng Trốp B, Xã An Hiệp, Châu Thành ,Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.905368,9.609761]
      },
      "properties": {
        "title": "THANH HUỆ",
        "description": "ấp Kinh Mới, Xã An Ninh, Huyện Châu Thành, Tỉnh Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.883014,9.887847]
      },
      "properties": {
        "title": "THANH LONG",
        "description": "ấp Hòa Lợi, xã Xuân Hòa, huyện Kế Sách, tỉnh Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.009831,9.683334]
      },
      "properties": {
        "title": "  TRƯƠNG THÀNH TÍN",
        "description": "xã Trường Khánh, Huyện Long Phú, Tỉnh Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.846558,9.631961]
      },
      "properties": {
        "title": "PHẠM VĂN SÁU",
        "description": "ấp Xẻo Gừa, Xã Mỹ Hương, huyện Mỹ Tú, Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.793640,9.640139]
      },
      "properties": {
        "title": "THÁI VINH",
        "description": "92 Hùng Vương, Nội Ô, Thị Trấn Huỳnh Hữu Nghĩa, huyện Mỹ Tú, Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.990649,9.559813]
      },
      "properties": {
        "title": "HUỲNH VÀNG",
        "description": "120 Tỉnh Lộ 8, ấp Thạnh Lợi, Thị Trấn Mỹ Xuyên, huyên Mỹ Xuyên, Tỉnh Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.693058,9.415129]
      },
      "properties": {
        "title": "MỸ CHÊN",
        "description": "ấp Kinh Ngay 1, thị trấn Hưng Lợi, huyện Thạnh Trị, tỉnh Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [106.149368,9.442472]
      },
      "properties": {
        "title": "KHÁNH HƯNG",
        "description": "ấp Giồng Giữa, Thị Trấn Lịch Hội Thượng, Huyện Trần Đề, Tỉnh Sóc Trăng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "SÓC TRĂNG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.606676,9.559471]
      },
      "properties": {
        "title": "CHÍ DŨNG",
        "description": "khóm 1, phường 1, thị xã Ngã Năm, tỉnh Sóc Trăng",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "QUẢNG TRỊ",
      "geometry": {
        "type": "Point",
        "coordinates": [107.082574,16.923979]
      },
      "properties": {
        "title": "VÕ THỊ PHƯƠNG MAI",
        "description": "Khu phố 7, Thị trấn Gio Linh, Huyện Gio Linh, Tỉnh Quảng Trị",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG TRỊ",
      "geometry": {
        "type": "Point",
        "coordinates": [107.176673,16.670469]
      },
      "properties": {
        "title": "CTY TNHH THU NGHĨA",
        "description": "Thôn Long Hưng, Xã Hải Phú, Huyện Hải Lăng, Tỉnh Quảng Trị",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG TRỊ",
      "geometry": {
        "type": "Point",
        "coordinates": [107.202336,16.701383]
      },
      "properties": {
        "title": "THU NGHĨA",
        "description": "Xã Hải Phú, Huyện Hải Lăng, Tỉnh Quảng Trị",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG TRỊ",
      "geometry": {
        "type": "Point",
        "coordinates": [106.5860307,16.6745874]
      },
      "properties": {
        "title": "XUÂN TRIỀU",
        "description": "thôn Tân Vĩnh, xã Hướng Tân, huyện Hướng Hóa, tỉnh Quảng Trị",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG NGÃI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.7801635,15.12077]
      },
      "properties": {
        "title": "CTY CP VTKT NLN QUẢNG NGÃI",
        "description": "94 Nguyễn Chánh, Phường Trần Phú, Thành phố Quãng Ngãi",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG NAM",
      "geometry": {
        "type": "Point",
        "coordinates": [108.3591102,15.7427936]
      },
      "properties": {
        "title": "DUYÊN HOA",
        "description": "366 Phạm Phú Thứ, Thị trấn Hà Lam, Huyện Thăng Bình, Tỉnh Quảng Nam",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG BÌNH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.476300,17.477338]
      },
      "properties": {
        "title": "TOÀN LOAN",
        "description": "Tiểu khu 1, TT. Nông trường Việt Trung, Bố Trạch, Quảng Bình",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG BÌNH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.737553,17.2420132]
      },
      "properties": {
        "title": "HIÊN QUYẾT",
        "description": "TT. Đại Phong, xã Phong Thủy, H Lệ Thủy, T Quảng Bình",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG BÌNH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.670229,17.273068]
      },
      "properties": {
        "title": "ANH CHIỆU",
        "description": "Vạn Ninh, Quảng Ninh, Quảng Bình",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "QUẢNG BÌNH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.3465587,17.6102766]
      },
      "properties": {
        "title": "PHƯƠNG TÂM",
        "description": "Thôn Tam Đa, Xã Tiến Hóa, Huyện Tuyên Hóa, Tỉnh Quảng Bình",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "PHÚ YÊN",
      "geometry": {
        "type": "Point",
        "coordinates": [109.29094,13.079288]
      },
      "properties": {
        "title": "ĐỨC HÙNG",
        "description": "Thôn Đông Phước, xã Hòa An, huyện Phú Hòa,Tỉnh Phú Yên",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "PHÚ YÊN",
      "geometry": {
        "type": "Point",
        "coordinates": [109.062016,12.976066]
      },
      "properties": {
        "title": "ĐÀO GIA VIÊN",
        "description": "Thôn Sơn Trường, Xã Sơn Thành Tây, Huyện Tây Hòa, Tỉnh Phú Yên",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "PHÚ YÊN",
      "geometry": {
        "type": "Point",
        "coordinates": [109.2925327,13.0901758]
      },
      "properties": {
        "title": "HÙNG CƯỜNG LOAN",
        "description": "Khu Phố Phước Hậu 3, Đường Nguyễn Tất Thành, Phường 9, Tp Tuy Hòa, Tỉnh Phú Yên",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "PhnomPenh",
      "geometry": {
        "type": "Point",
        "coordinates": [104.9201698,11.5603439]
      },
      "properties": {
        "title": "YETAK",
        "description": "No 49D, Street 214, Sangkat boeung Raing, Khan Daun Penh, Phnom Penh, Cambodia",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "NINH THUẬN",
      "geometry": {
        "type": "Point",
        "coordinates": [108.762224,11.793592]
      },
      "properties": {
        "title": "BẠCH THỊ THU CẨM",
        "description": "Thôn Trà Giang 3, xã Lương Sơn, huyện Ninh Sơn, tỉnh Ninh Thuận",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "NINH THUẬN",
      "geometry": {
        "type": "Point",
        "coordinates": [108.7332047,11.7973796]
      },
      "properties": {
        "title": "TRẦN VĂN TIẾN",
        "description": "Thôn Trà Giang 4, xã Lương Sơn, huyện Ninh Sơn, tỉnh Ninh Thuận",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "NINH THUẬN",
      "geometry": {
        "type": "Point",
        "coordinates": [108.9950695,11.5650372]
      },
      "properties": {
        "title": "THANH HOA",
        "description": "TN46 Thống Nhất, KP6, Phường Đạo Long, TP Phan Rang, Tháp Chàm, Ninh Thuận",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "NINH THUẬN",
      "geometry": {
        "type": "Point",
        "coordinates": [108.9645144,11.6044474]
      },
      "properties": {
        "title": "THANH VÂN",
        "description": "Thôn Tân Sơn 2, Xã Thành Hải, Tp Phan Rang- Tháp Chàm, Tỉnh Ninh Thuận",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "NAM ĐỊNH",
      "geometry": {
        "type": "Point",
        "coordinates": [105.131440,19.410801]
      },
      "properties": {
        "title": "NHƯƠNG THỦY",
        "description": "Nghệ An",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "NAM ĐỊNH",
      "geometry": {
        "type": "Point",
        "coordinates": [105.6573441,18.6671587]
      },
      "properties": {
        "title": "TĂNG HUY CƯỜNG 2",
        "description": "Số 55A đường Nguyễn Sinh Sắc, phường Cửa Nam, thành phố Vinh, tỉnh Nghệ An",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "NAM ĐỊNH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.066457,20.280138]
      },
      "properties": {
        "title": "TẤN ANH",
        "description": "Thôn Tam Quang, Xã Yên Thắng, Huyện ý Yên, Tỉnh Nam Định",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [106.520386,10.634845]
      },
      "properties": {
        "title": "LONG HIỆP",
        "description": "Km 1929, Quốc Lộ 1, Bến Lức, Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [106.071456,10.752583]
      },
      "properties": {
        "title": "NGÔ THỊ HỒNG CHÂU",
        "description": "ấp 1, xã Bình Phong Thạnh, huyện Mộc Hóa, tỉnh Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [105.799538,10.883811]
      },
      "properties": {
        "title": "NGUYỄN ANH THÁI",
        "description": "Số 60, ấp Sậy Giăng, xã Vĩnh Trị, huyện Vĩnh Hưng, tỉnh Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [106.411333,10.523436]
      },
      "properties": {
        "title": "CTY THỊNH THẾ THÀNH",
        "description": "294 Khu phố An Thuận 2, P. 7, TP. Tân An, T. Long An",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [106.418472,10.532618]
      },
      "properties": {
        "title": "THỊNH THẾ THÀNH",
        "description": "Số 294, tỉnh lộ 827,khu phố An Thuận 2, Phường 7, Thành Phố Tân An, Tỉnh Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [105.938527,10.779563]
      },
      "properties": {
        "title": "BA XÊ HIỆP LỢI",
        "description": "Số 96,  Bạch Đằng, Khu phố 1, Phường 1, Thị xã Kiến Tường, Mộc Hóa, Tỉnh Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [105.928863,10.774999]
      },
      "properties": {
        "title": "NĂM THEO",
        "description": "287A, khu phố 1, phường 3, thị xã Kiến Tường, tỉnh Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LONG AN",
      "geometry": {
        "type": "Point",
        "coordinates": [105.881919,10.743656]
      },
      "properties": {
        "title": "NGỌC SANG",
        "description": "ấp Bàu Môn, Xã Thạnh Hưng, Thị xã Kiến Tường,Tỉnh Long An",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÀO CAI",
      "geometry": {
        "type": "Point",
        "coordinates": [103.973142,22.500047]
      },
      "properties": {
        "title": "VŨ XUÂN HUỲNH",
        "description": "CN 15, Lô K13, Triệu Quang Phục, CCN Đông Phố Mới, P. Phố Mới, TP. Lào Cai",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [107.804468,11.431015]
      },
      "properties": {
        "title": "MINH UYÊN",
        "description": "Thôn 9, Xã Lộc Thành, Huyện Bảo Lâm, Tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1138045,11.9282485]
      },
      "properties": {
        "title": "QUỲNH GIAO",
        "description": "Thôn Trung Tâm, Quốc Lộ 27, Xã Đạ KNàng, Huyện Đam Rông, Tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.527088,11.738022]
      },
      "properties": {
        "title": "GIANG",
        "description": "thôn Quảng Lợi, xã Quảng Lập, huyện Đơn Dương, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.5079717,11.7494473]
      },
      "properties": {
        "title": "HỒNG - LIÊN ",
        "description": "Số 92, Thôn Quảng Hòa, Xã Quảng Lập, Huyện Đơn Dương, Tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.5165632,11.7592412]
      },
      "properties": {
        "title": "LINH ĐẠO",
        "description": "Thôn Nghĩa Hiêp 1, Xã Ka Đô, Huyện Đơn Dương, Tỉnh Lâm Đồng, Ka Do, Đơn Dương, Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.5742331,11.8026555]
      },
      "properties": {
        "title": "MINH DƯƠNG",
        "description": "số 68/74, thôn Kinh Tế Mới Châu Sơn, xã Lạc Xuân, huyện Đơn Dương, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4809209,11.7262625]
      },
      "properties": {
        "title": "NGUYỄN VĂN THƯƠNG",
        "description": "Thôn Sao Mai, Xã Ka Đơn, Huyện Đơn Dương, Tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4597778,11.7350354]
      },
      "properties": {
        "title": "THIỆN THANH",
        "description": "số 98, thôn Suối Thông B1, xã Đạ Ròn, huyện Đơn Dương, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.5432026,11.8799263]
      },
      "properties": {
        "title": "TOÀN PHƯỢNG",
        "description": "số 01, đường Bà Triệu, thị trấn Dran, huyện Đơn Dương, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4135035,11.7858979]
      },
      "properties": {
        "title": "NGUYỄN PHI HÙNG",
        "description": "10/13, thôn Finôm, xã Hiệp Thạnh, huyện Đức Trọng, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.3844098,11.7558703]
      },
      "properties": {
        "title": "NGUYỄN THỊ MỪNG",
        "description": "41 Lê Văn Tám, KP6, TT. Liên Nghĩa, huyện Đức Trọng, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.3772356,11.7475043]
      },
      "properties": {
        "title": "NHƯ LINH",
        "description": "Số 350, khu phố 4, Thị trấn Liên Nghĩa, Huyện Đức Trọng, Tỉnh Lâm Đồng, Việt Nam",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.3500646,11.9087936]
      },
      "properties": {
        "title": "HÒA ÁI",
        "description": "Thôn 1, Xã Đạ Sar, Huyện Lạc Dương, Tỉnh Lâm Đồng, Đạ Sar, Lạc Dương, Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1888526,11.749122]
      },
      "properties": {
        "title": "BẢO ANH",
        "description": "24A, Thôn Tân Đức, Xã Tân Hà, Huyện Lâm Hà, Tỉnh Lâm Đồng",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.163488,11.888151]
      },
      "properties": {
        "title": "NGUYỄN THỊ KIM LOAN",
        "description": "75 Thôn Ngọc Sơn, Xã Phú Sơn, Huyện Lâm hà, Tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1185824,11.7008787]
      },
      "properties": {
        "title": "QUANG THƠM",
        "description": "Thôn Liên Kết, xã Liên Hà, Huyện Lâm Hà, tỉnh Lâm Đồng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.560822,11.8837559]
      },
      "properties": {
        "title": "HUỲNH QUỐC HÙNG",
        "description": "117/5 Trường Thọ, Trạm Hành, Đà Lạt",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "LÂM ĐỒNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4320539,11.9503343]
      },
      "properties": {
        "title": "KIM ANH",
        "description": "Số 58 KQH dân cư Phan Đình Phùng, Nguyễn Công Trứ, Phường 2, Đà Lạt, Tỉnh Lâm Đồng",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "KONTUM",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0065381,14.3582735]
      },
      "properties": {
        "title": "ANH THI",
        "description": "215 Trần Nhân Tông, P. Thắng Lợi, TP Kon Tum, Tỉnh Kon Tum",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.020493,9.778774]
      },
      "properties": {
        "title": "NAM THUẬN",
        "description": "Tổ 4, ấp Phú hưởng, xã Đông Thái, Huyện An Biên, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.108458,9.859730]
      },
      "properties": {
        "title": "TRUNG HIỆP",
        "description": "331, ấp Xẻo rô, xã Hưng Yên, huyện An Biên, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.963046,9.674216]
      },
      "properties": {
        "title": "NGỌC BÍCH",
        "description": "ấp Thạnh An, Đông Thạnh, An Minh, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.943424,9.617703]
      },
      "properties": {
        "title": "QUỐC THẢO",
        "description": "Khu Vực I, Thị trấn thứ 11, An Minh, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.959796,9.580720]
      },
      "properties": {
        "title": "TRƯƠNG MINH",
        "description": "ấp Vàm Xáng, Đông Hưng, An Minh, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.757536,10.489657]
      },
      "properties": {
        "title": "CHÍN LỢP",
        "description": "Tổ 2, ấp T4, Xã Vĩnh Phú, H. Giang Thành, Tỉnh KiênGiang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.597439,10.482488]
      },
      "properties": {
        "title": "NĂM ĐUM",
        "description": "Tổ 2, ấp Giồng Kè, xã Phú Lợi, huyện Giang Thành, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.489821,9.919854]
      },
      "properties": {
        "title": "PHƯƠNG MINH",
        "description": "526, ấp Hòa B, xã Hòa Lợi, huyện Giồng Riềng, tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.297962,9.895281]
      },
      "properties": {
        "title": "SÁU ĐIỆP",
        "description": "TT. Giồng Riềng, Giồng Riềng, tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.259192,9.939918]
      },
      "properties": {
        "title": "THÀNH NHANH",
        "description": "Số 10, tổ 1, ấp Sở Tại, Xã Bàn Tân Định, Huyện Giồng Riềng, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.872850,10.246492]
      },
      "properties": {
        "title": "DUY PHONG",
        "description": "Bình Thuận, Bình Sơn, Hòn Đất, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.066753,10.057683]
      },
      "properties": {
        "title": "HUỲNH THỊ HOAN",
        "description": "712, ấp Tân Điền, Xã Mỹ Lâm, Huyện Hòn Đất, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.814399,10.259921]
      },
      "properties": {
        "title": "LÊ HOÀNG ĐẠT",
        "description": "Tổ 7, ấp Bình Thuận, xã Bình Sơn, huyện Hòn Đất, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [104.922812,10.186463]
      },
      "properties": {
        "title": "NĂM LOẠN",
        "description": "Số 212, tổ 6, Khu Phố  Đường Hòn, T.T Hòn Đất, H. Hòn Đất, T. Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.066635,10.057387]
      },
      "properties": {
        "title": "TÂN THÀNH",
        "description": "Số 712, ấp Tân Điền, Xã Mỹ Lâm, Huyện Hòn Đất, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.242757,10.074689]
      },
      "properties": {
        "title": "ĐÌNH KIÊN",
        "description": "ấp Kinh 8B, xã Thạnh Đông, huyện Tân Hiệp, tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.221137,10.055294]
      },
      "properties": {
        "title": "ĐỨC TUẤN",
        "description": "ấp Đông Lộc, xã Thạnh Đông, huyện Tân Hiệp, tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.291477,10.112081]
      },
      "properties": {
        "title": "THẮNG TRANG",
        "description": "Thị Trấn Tân Hiệp, Tân Hịêp, tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.139889,9.689507]
      },
      "properties": {
        "title": "LÊ THANH NGUYÊN",
        "description": "Tổ 4, số nhà 115, ấp Cạn Ngon, xã Thạnh Yên, Huyện U Minh Thượng, T. Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.243009,9.513837]
      },
      "properties": {
        "title": "CHƯƠNG NGA",
        "description": "ấp Vĩnh Phước II, Thị trấn Vĩnh Thuận, Huyện Vĩnh Thuận, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.234007,9.476121]
      },
      "properties": {
        "title": "LIÊN MINH",
        "description": "ấp Vĩnh Tây, xã Vĩnh Phong, huyện Vĩnh Thuận, Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.255889,9.514259]
      },
      "properties": {
        "title": "VƯƠNG NGUYÊN",
        "description": "ấp Vĩnh Đông 2, Thị Trấn Vĩnh Thuận, Huyện Vĩnh Thuận, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KIÊN GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.118985,9.953676]
      },
      "properties": {
        "title": "TRẦN TÂN",
        "description": "63 Nguyễn Chí Thanh, Phường Rạch Sỏi, Tỉnh Kiên Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "KHÁNH HÒA",
      "geometry": {
        "type": "Point",
        "coordinates": [109.0990283,12.2579549]
      },
      "properties": {
        "title": "ĐINH THỊ THỦY",
        "description": "Đội 4, Diên An, Diên Khánh, Khánh Hoà",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HUẾ",
      "geometry": {
        "type": "Point",
        "coordinates": [107.5618255,16.452988]
      },
      "properties": {
        "title": "NÔNG VIỆT",
        "description": "245H Bùi Thị Xuân, Phường Thủy Xuân, Thành Phố Huế, Tỉnh Thừa Thiên Huế",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HUẾ",
      "geometry": {
        "type": "Point",
        "coordinates": [107.5475709,16.4832119]
      },
      "properties": {
        "title": "TUYẾT NHƯ",
        "description": "11 Lý Thái Tổ, Thành Phố Huế, Tỉnh Thừa Thiên Huế",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HỒ CHÍ MINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.670644,10.778466]
      },
      "properties": {
        "title": "BÌNH ĐIỀN VƯƠN XANH",
        "description": "Quận 10, Thành Phố Hồ Chí Minh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HỒ CHÍ MINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.495126,10.964714]
      },
      "properties": {
        "title": "PHAN THỊ BÉ",
        "description": "QL 22, huyện Củ Chi, Hồ Chí Minh",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HỒ CHÍ MINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.664347,10.774428]
      },
      "properties": {
        "title": "VƯƠN XANH",
        "description": "đường Thành Thái, Quận 10, Thành Phố Hồ Chí Minh",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "HỒ CHÍ MINH",
      "geometry": {
        "type": "Point",
        "coordinates": [106.734906, 10.793177]
      },
      "properties": {
        "title": "HIẾU GIANG",
        "description": "22-24 Đường số 9, Khu phố 4, Phường An Phú, Quận 2, Thành Phố Hồ Chí Minh",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.628554,9.940259]
      },
      "properties": {
        "title": "TRUNG TÍCH",
        "description": "ấp nhơn Thuận 1B, xã Nhơn Nghĩa A, huyện Châu Thành, Tỉnh Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.657080,9.908747]
      },
      "properties": {
        "title": "  LÊ QUANG TRÍ",
        "description": "Thị trấn Rạch Gòi, Châu Thành A, Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.8004739,9.9189226]
      },
      "properties": {
        "title": "TUẤN HẰNG",
        "description": "ấp Thuận Hưng, Thị Trấn Ngã Sáu, huyện Châu Thành, Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.459020,9.776456]
      },
      "properties": {
        "title": "NGUYỄN VĂN VO",
        "description": "551 Trần Hưng Đạo, Khu vực 1, Phường III, Vị Thanh, Tỉnh Hậu Giang",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.7166369,9.7803451]
      },
      "properties": {
        "title": "NĂM BÙI",
        "description": "ấp Mỹ Qưới, thị trấn Cây Dương, huyện Phụng Hiệp, tỉnh Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.8052312,9.8052865]
      },
      "properties": {
        "title": "NHÂN LINH",
        "description": "Số 180 đường 30/4 , khu vực II, phường Lái Hiếu, thị xã Ngã Bảy, Tinh Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.7724003,9.8053745]
      },
      "properties": {
        "title": "PHẠM THANH TÙNG",
        "description": "ấp Mỹ Quới, Thị Trấn Cây Dương, huyện Phụng Hiệp, Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.465408,9.783240]
      },
      "properties": {
        "title": "KIM NGUYÊN",
        "description": "Số 116, đường Nguyễn Huệ, khu vực 5, phường IV, Thành Phố Vị Thanh, Tỉnh Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.570647,9.681940]
      },
      "properties": {
        "title": "LÂM ANH",
        "description": "63 Trần Hưng Đạo, KV Bình Thạnh B, Phường Bình Thạnh, Thị xã Long Mỹ, Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HẬU GIANG",
      "geometry": {
        "type": "Point",
        "coordinates": [105.833906,9.859946]
      },
      "properties": {
        "title": "NGUYỄN QUỐC TOÀN",
        "description": "ấp Sơn Phú 2A, xã Tân Thành, thị xã Ngã bảy, tỉnh Hậu Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HÀ NỘI",
      "geometry": {
        "type": "Point",
        "coordinates": [105.6620829,21.0310864]
      },
      "properties": {
        "title": "THÁI HÀ AN",
        "description": "Thôn 3, xã Song Phương, Huyện Hoài Đức, TP Hà Nội",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "HÀ NỘI",
      "geometry": {
        "type": "Point",
        "coordinates": [105.8468437,21.0204518]
      },
      "properties": {
        "title": "THÁI SƠN",
        "description": "03 Trương Hán Siêu, Quận Hoàn Kiếm, Hà Nội",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.759998,14.170848]
      },
      "properties": {
        "title": "LAN ANH",
        "description": "Thôn la Lôk, Ia Mơ Nông, Chư Păh, Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.8774112,13.7562991]
      },
      "properties": {
        "title": "HƯỜNG DƯỠNG",
        "description": "281 Hùng Vương, TT. Chư Prông, huyện Chư Prông, Tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.9720707,14.0439069]
      },
      "properties": {
        "title": "MINH BÌNH",
        "description": "Làng Nang, Xã Ia Sao, Huyện Ia Grai, tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.122613,13.598724]
      },
      "properties": {
        "title": "DUY LƯƠNG",
        "description": "Thôn Bletacho, xã Ia Hrú, Chư Pưh, Gia Lai ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0928483,13.6611949]
      },
      "properties": {
        "title": "LÊ THƯƠNG",
        "description": "Thôn 4, xã Ia Pal, huyện Chư Sê, tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1093643,14.0000757]
      },
      "properties": {
        "title": "THU HÀ",
        "description": "Đường Lý Thường Kiệt, Tổ dân phố 7, thị trấn Đăk Đoa, Huyện Đak Đoa, Tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.687387,13.797322]
      },
      "properties": {
        "title": "VĨNH TRANG",
        "description": "Chư Ty, Đức Cơ, Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.9984881,13.9826675]
      },
      "properties": {
        "title": "CHẾ HOA",
        "description": "117 Phan Đình Phùng, P. Yên Đỗ, Thành phố Pleiku, Tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.9903729,13.9736876]
      },
      "properties": {
        "title": "ĐOÀN THỊ XANH",
        "description": "11/9 Nguyễn Văn Cừ, phường IaKring, thành phố Pleiku, Tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [107.957542,13.9737736]
      },
      "properties": {
        "title": "HÓA SINH SÀI GÒN",
        "description": "Thôn Hàm Rồng, Xã Chư Hdrông, Chi Lăng, Thành phố Pleiku, Tỉnh Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.078144,13.978563]
      },
      "properties": {
        "title": "NGUYỄN THỊ NHUNG",
        "description": "Thôn 01, Xã An phú, Thành Phố Pleiku, Gia Lai",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.6632296,13.9519664]
      },
      "properties": {
        "title": "PHÚ NÔNG",
        "description": "Số 90, Đường Trần Quang Diệu, Phường An Phú, thị Xã An Khê, Gia Lai",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "GIA LAI",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4401187,13.403162]
      },
      "properties": {
        "title": "BẢO KHANH",
        "description": "163 Lê Hồng Phong, Thị xã Ayun Pa, Tỉnh Gia Lai",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐỒNG THÁP",
      "geometry": {
        "type": "Point",
        "coordinates": [105.823330,10.238483]
      },
      "properties": {
        "title": "SÁU CÔNG",
        "description": "527 tổ 1, ấp Tân Hựu, xã Tân Nhuận Đông, Châu Thành, Đồng Tháp",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐỒNG THÁP",
      "geometry": {
        "type": "Point",
        "coordinates": [105.606276,10.265387]
      },
      "properties": {
        "title": "VŨ TRINH",
        "description": "ấp Tân Bình, xã Tân Thành, huyện Lai Vung, Tỉnh Đồng Tháp",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐỒNG THÁP",
      "geometry": {
        "type": "Point",
        "coordinates": [105.542623,10.716176]
      },
      "properties": {
        "title": "BÙI THỊ THÊU",
        "description": "111, ấp 1, Tam Nông, Đồng Tháp",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐÀ NẴNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.2140333,16.0815011]
      },
      "properties": {
        "title": "TRẦN THỊ THÊM",
        "description": "110 Hải Hồ, Quận Hải Châu, Tp Đà Nẵng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐÀ NẴNG",
      "geometry": {
        "type": "Point",
        "coordinates": [108.185621,16.050650]
      },
      "properties": {
        "title": "MAI NGÂN",
        "description": "An Khê, Thanh Khê, Đà Nẵng",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK NÔNG",
      "geometry": {
        "type": "Point",
        "coordinates": [107.894372,12.586050]
      },
      "properties": {
        "title": "HỒNG NGỌC",
        "description": "Số 19, Hùng Vương, tổ 1, khối 5, thị trấn EaTling, Huyện Cư Jút, Đắk Nông",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK NÔNG",
      "geometry": {
        "type": "Point",
        "coordinates": [107.867469,12.657620]
      },
      "properties": {
        "title": "NGUYỄN THỊ BÌNH",
        "description": "Thôn 8, Xã Nam Dong, Huyện Cư Jút , Tỉnh Đăk Nông",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK NÔNG",
      "geometry": {
        "type": "Point",
        "coordinates": [107.6603079,12.4442875]
      },
      "properties": {
        "title": "NAM THUẬN",
        "description": "Thôn Hòa Phong, Xã Đắk Sắk , Huyện Đắk Mil, Tỉnh Đắk Nông",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK NÔNG",
      "geometry": {
        "type": "Point",
        "coordinates": [107.6155686,12.4537322]
      },
      "properties": {
        "title": "THÀNH MAI",
        "description": "Số 61, Đường Nguyễn Chí Thanh, Thị Trấn Đắk Mil, Huyện Đắk Mil, Tỉnh Đắk Nông",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK NÔNG",
      "geometry": {
        "type": "Point",
        "coordinates": [107.729222,11.956606]
      },
      "properties": {
        "title": "HÙNG TIẾN",
        "description": "Bon PhaiKal PruĐăng, xã ĐăkNia, TX Gia Nghĩa, Tỉnh ĐăkNông",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [107.819352,12.865266]
      },
      "properties": {
        "title": "NGUYỄN XUÂN THANH",
        "description": "Buôn Rếch A, Xã Ea Huar, huyện Buôn Đôn, tỉnh Đăk Lăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1636464,12.5747102]
      },
      "properties": {
        "title": "HOÀNG VŨ",
        "description": "Thôn 4, xã Ea B hốk , huyện Cư Kuin, Tỉnh Đăklăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0897829,12.5978694]
      },
      "properties": {
        "title": "QUANG THIỀU",
        "description": "Thôn 8, Xã Ea Tiêu, Huyện Cư Kuin, Tỉnh Đắk Lắk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.069162,12.905730]
      },
      "properties": {
        "title": "TUẤN CƯỜNG",
        "description": "BUÔN EASANG, XÃ EA HDING",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.2017887,13.2057294]
      },
      "properties": {
        "title": "ANH MĂNG",
        "description": "Khối 7, Thị Trấn Ea Drăng, Huyện Ea H'Leo, TT. Ea Drăng, Ea H'Leo, Đắk Lắk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1339369,13.2058922]
      },
      "properties": {
        "title": "EAWY",
        "description": "Thôn 6, Xã Ea Wy, Huyện Ea H'Leo, Tỉnh Đắk Lắk, Ea Wy, Ea H'Leo, Đắk Lắk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [107.9153067,13.2782017]
      },
      "properties": {
        "title": "TÂN DIỄM",
        "description": "Thôn 7, Xã Cư Mốt, Huyện Ea H'Leo, Tỉnh Đắk Lắk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4815479,12.7089814]
      },
      "properties": {
        "title": "CÀ PHÊ 716",
        "description": "Thôn 8, Xã Ea Ô, huyện Eakar, Tỉnh Đaklak",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4202622,12.7091605]
      },
      "properties": {
        "title": "NÔNG HƯƠNG",
        "description": "Thôn 14, xã Eaô, huyện EaKar, tỉnh ĐăkLăk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.4270413,12.8009092]
      },
      "properties": {
        "title": "QUANG HUYỀN",
        "description": "Thôn Đoàn Kết, Xã EaKmút, Huyện EaKa, Tỉnh ĐăkLăk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0174062,12.4845557]
      },
      "properties": {
        "title": "BÌNH YÊN",
        "description": "Buôn Êcăm, TT Buôn Trấp, Krông Ana, ĐăkLăk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [107.958252,12.554425]
      },
      "properties": {
        "title": "QUÁCH HẢI",
        "description": "Xã Eana, Huyện Krông Ana, Tỉnh Đăklăk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.244121,12.972737]
      },
      "properties": {
        "title": "NGUYÊN NGHĨA",
        "description": "Thôn 7, Xã Pơng Đrang, Huyện Krông Buk, Tỉnh Đắk lắk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.380761,13.008199]
      },
      "properties": {
        "title": "CHƯƠNG KIỀU",
        "description": "Thôn Tân Thành, xã EaTóh, huyện Krông Năng, Tỉnh ĐăkLăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.365069,12.728783]
      },
      "properties": {
        "title": "ĐỨC VUI",
        "description": "Km38, Xã Ea phê, Krông Pắc, Đắk Lắk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.306833,12.709245]
      },
      "properties": {
        "title": "TRÚC PHƯỢNG",
        "description": "Thị Trấn Phước An, huyện Krông Pắk, tỉnh ĐăkLăk",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0658362,12.3211497]
      },
      "properties": {
        "title": "MINH ĐÔ",
        "description": "Buôn Phi Dih JaB, Xã Krông Nô, Huyện Lắk, Tỉnh Đăk Lăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1603146,12.4069663]
      },
      "properties": {
        "title": "TRẦN THỊ NGA",
        "description": "Thôn Hòa Thắng, Thị Trấn Liên Sơn, Huyện Lăk, Tỉnh Đăk lăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.7478909,12.7367436]
      },
      "properties": {
        "title": "MẠNH HUẤN",
        "description": "344, Tổ 1, Đường Nguyễn Tất Thành, Thị Trấn M'Drắk, huyện M'Drắk, Tỉnh Đăk Lăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0414273,12.6841269]
      },
      "properties": {
        "title": "CÔNG NGUYÊN",
        "description": "132 Lý Thường Kiệt, TP. Buôn Mê Thuột, ĐăkLăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1055156,12.6544392]
      },
      "properties": {
        "title": "HUY CHÍNH",
        "description": "214 Nguyễn Thái Bình, TP. Buôn Mê Thuột, Tỉnh ĐăkLăk",
        "marker-color": "#ff0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0024413,12.7004773]
      },
      "properties": {
        "title": "NINACAFE",
        "description": "Thôn 10, Xã Hòa Thắng, TP Buôn Ma Thuột, T Đăk Lăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.121296,12.658788]
      },
      "properties": {
        "title": "PHONG VÂN",
        "description": "Thôn 4, xã Hòa Xuân, Thành Phố Buôn Ma Thuột, Tỉnh Đăklăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1094652,12.6588504]
      },
      "properties": {
        "title": "TÂN CƯỜNG THỊNH",
        "description": "Thôn 4, Xã Hòa Xuân, Tp Buôn Mê Thuột, Đăklăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0527727,12.6913699]
      },
      "properties": {
        "title": "THỊNH THÀNH",
        "description": "B8, Đường Tôn Đức Thắng, P Tân lợi, Tp Buôn Ma Thuột, Đắklắk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0450886,12.6870482]
      },
      "properties": {
        "title": "THÙY DƯƠNG",
        "description": "53/7C Trần Hưng Đạo, Phường Tự An, Tp Buôn Ma Thuột, Đăklăk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0440873,12.6799575]
      },
      "properties": {
        "title": "TRẦN THỊ BÚP",
        "description": "09 Hùng Vương, Phường Tự An, Tp Buôn Mê Thuột , Tỉnh Đăklăk",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.0708084,12.6861148]
      },
      "properties": {
        "title": "XUÂN DUNG",
        "description": "289 Nguyễn Văn Cừ, Phường Tân Lập, Tp Buôn Mê Thuột, Đăklăk",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.2781601,12.9295534]
      },
      "properties": {
        "title": "CÀ PHÊ BUÔN HỒ",
        "description": "Km2, Đường Trần Hưng Đạo, Phường Đạt Hiếu,TX  Buôn Hồ, Tỉnh ĐakLak",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "ĐẮK LẮK",
      "geometry": {
        "type": "Point",
        "coordinates": [108.2091975,12.8507221]
      },
      "properties": {
        "title": "HOA TƯỜNG",
        "description": "Khối Đồng Tâm, P.An Lạc, TX Buôn Hồ, tỉnh ĐắkLắk",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Champasak",
      "geometry": {
        "type": "Point",
        "coordinates": [105.823199,15.109591]
      },
      "properties": {
        "title": "CTY TNHH CAO SU ĐẮK LẮK",
        "description": "Bản Thaluong, Thành phố Pakse, tỉnh Champasak, Lào",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.391509,10.1326611]
      },
      "properties": {
        "title": "PHƯƠNG MAI",
        "description": "ấp Thới Thuận, T.T Cờ Đỏ, Huyện Cờ Đỏ, Tp Cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.534503,10.006052]
      },
      "properties": {
        "title": "HIỆP HƯNG",
        "description": "ấp Phú Thọ, Xã Trường Xuân, Huyện Thới Lai, Thành Phố Cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.525036,9.981286]
      },
      "properties": {
        "title": "MƯỜI NỮA",
        "description": "ấp Trường Ninh, Xã Trường Xuân B, Huyện Thới Lai, Cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.4849642,9.9870545]
      },
      "properties": {
        "title": "TIỀN DIỆP",
        "description": "ấp Trường Ninh 3, Xã Trường Xuân A, Huyện Thới Lai, Thành Phố Cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.441695,10.249383]
      },
      "properties": {
        "title": "THẦN NÔNG 18",
        "description": "ấp Vĩnh Tiến, Thị trấn Vĩnh Thạnh, huyện Vĩnh Thạnh, TP Cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.504939,10.290208]
      },
      "properties": {
        "title": "BÉ TƯ",
        "description": "Khu vực Thới Hòa, Phường Thới Thuận, Quận Thốt Nốt, Thành Phố Cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CẦN THƠ",
      "geometry": {
        "type": "Point",
        "coordinates": [105.5310868,10.2684857]
      },
      "properties": {
        "title": "KHUYA",
        "description": "Khu Vực Phụng Thạnh 1, P. Thốt Nốt, Q. Thốt Nốt, cần Thơ",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "CÀ MAU",
      "geometry": {
        "type": "Point",
        "coordinates": [105.1472765,9.1852214]
      },
      "properties": {
        "title": "VƯƠN XANH 2",
        "description": "số 75/10, đường Nguyễn Thiện Năng, Khóm 3, Phường 4, TP Cà Mau, Tỉnh Cà Mau",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "BÌNH THUẬN",
      "geometry": {
        "type": "Point",
        "coordinates": [108.1202612,10.9686673]
      },
      "properties": {
        "title": "THIÊN PHÚC",
        "description": "Tổ 3, Thôn Hòa Thắng, Xã Hàm Thắng, Huyện Hàm Thuận Bắc, Tỉnh Bình Thuận",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BÌNH PHƯỚC",
      "geometry": {
        "type": "Point",
        "coordinates": [106.8773929,11.5152116]
      },
      "properties": {
        "title": "TIẾN THÀNH",
        "description": "ấp 3, Xã Đồng Tiến, Huyện Đồng Phú, Tỉnh Bình Phước",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BÌNH ĐỊNH",
      "geometry": {
        "type": "Point",
        "coordinates": [109.074128,14.001895]
      },
      "properties": {
        "title": "ĐẶNG THỊ LÂM",
        "description": "Cát Trinh, Phù Cát, Bình Định",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BÌNH ĐỊNH",
      "geometry": {
        "type": "Point",
        "coordinates": [109.118920,13.880220]
      },
      "properties": {
        "title": "TÁM TRUNG",
        "description": "Số 441 Trần Phú, Khu phố Liêm Trực, Phường Bình Định, Thị xã An Nhơn, Tỉnh Bình Định",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BÌNH ĐỊNH",
      "geometry": {
        "type": "Point",
        "coordinates": [109.146289,13.802090]
      },
      "properties": {
        "title": "HỒNG NHUNG",
        "description": "Thôn Diêu Trì, Thị Trấn Diêu Trì, Huyện Tuy Phước, Tỉnh Bình Định",
        "marker-color": "#FF1493",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BẾN TRE",
      "geometry": {
        "type": "Point",
        "coordinates": [106.5646132,10.0665841]
      },
      "properties": {
        "title": "NGUYỄN KIM THỦ",
        "description": "ấp An Phú, Xã An Bình Tây, huyện Ba Tri, Tỉnh Bến Tre",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BẾN TRE",
      "geometry": {
        "type": "Point",
        "coordinates": [106.5114365,10.076607]
      },
      "properties": {
        "title": "TRƯƠNG VĂN BÌNH",
        "description": "ấp 1, xã An Ngãi Trung, huyện ba Tri, tỉnh Bến Tre",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BẾN TRE",
      "geometry": {
        "type": "Point",
        "coordinates": [106.378576,10.2351045]
      },
      "properties": {
        "title": "TRẦN THỊ NGOAN",
        "description": "Số 9, Đường Nguyễn Huệ, Phường Phú Khương, Thành phố Bến Tre, Tỉnh Bến Tre",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BẠC LIÊU",
      "geometry": {
        "type": "Point",
        "coordinates": [105.588102,9.2819609]
      },
      "properties": {
        "title": "TẠ THỊ NGA",
        "description": "ấp Thị Trấn B, Thị Trấn Hòa Bình, Huyện Hòa Bình, Tỉnh Bạc Liêu",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BẠC LIÊU",
      "geometry": {
        "type": "Point",
        "coordinates": [105.483035,9.2823555]
      },
      "properties": {
        "title": "SỸ OANH",
        "description": "ấp Tam Hưng, Xã Vĩnh Hưng, Huyện Vĩnh Lợi, Tỉnh Bạc Liêu",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "BẠC LIÊU",
      "geometry": {
        "type": "Point",
        "coordinates": [105.7021548,9.296546]
      },
      "properties": {
        "title": "THANH PHỤNG",
        "description": "Số 290, đường 23 tháng 8, phường 8, thành phố Bạc Liêu, tỉnh Bạc Liêu",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.0760101,10.7964678]
      },
      "properties": {
        "title": "CHÂU NHẬT QUANG",
        "description": "Số 380 Bạch Đằng, Thị Trấn An Phú, Huyện An Phú, Tỉnh An Giang",
        "marker-color": "#FF0000",
        "marker-size": "small",
        "marker-symbol": "1"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.1483789,10.5480126]
      },
      "properties": {
        "title": "BÁ QUÁT",
        "description": "Tổ 10, ấp Ba Xưa , xã Thạnh Mỹ Tây, Huyện Châu Phú, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.3215115,10.5204226]
      },
      "properties": {
        "title": "HAI LỐI 2",
        "description": "Tổ 14, ấp Bình Hòa, Xã Bình Thủy, Huyện Châu Phú, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.273651,10.521143]
      },
      "properties": {
        "title": "LÂM NGỌC NHỚ",
        "description": "Tổ 02, ấp Bình Tân, xã Bình Mỹ, Huyện Châu Phú, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.410364,10.511778]
      },
      "properties": {
        "title": "THANH NHÃ",
        "description": "số 112, tổ 11, ấp Kiến Thuận 2, xã Kiến Thành, Huyện Chợ Mới, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.3532949,10.5220147]
      },
      "properties": {
        "title": "XUÂN BÍCH",
        "description": "ấp Hòa Hạ, Xã Kiến An, huyện Chợ Mới, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.254854,10.5224192]
      },
      "properties": {
        "title": "NGUYỄN THỊ LỆ THƯƠNG",
        "description": "ấp Phú Vinh, Thị Trấn Chợ Vàm, Huyện Phú Tân, T. An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.3303145,10.6166469]
      },
      "properties": {
        "title": "THẾ MẪN",
        "description": "ấp Phú Mỹ Hạ, Xã Phú Thọ, Huyện Phú Tân, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.228767,10.606105]
      },
      "properties": {
        "title": "TƯ DƯƠNG",
        "description": "900, tổ 1, ấp Bình Phú 2, xã Phú Bình, Huyện Phú Tân, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.2690909,10.2857992]
      },
      "properties": {
        "title": "ĐỒNG PHÁT",
        "description": "Tỉnh lộ 943, tổ 13, ấp Thanh Niên, thị trấn Phú Hòa, Thoại Sơn, An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.382721,10.354705]
      },
      "properties": {
        "title": "KIM ĐIỀN (THOẠI SƠN)",
        "description": "Tổ 13, ấp Thanh Niên, Thị Trấn Phú Hòa, Huyện Thoại Sơn, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.0281607,10.5365533]
      },
      "properties": {
        "title": "BÙI CÔNG DANH",
        "description": "Tổ 4, Khóm 1, thị trấn Chi Lăng, huyện Tịnh Biên, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [104.978919,10.622826]
      },
      "properties": {
        "title": "NGUYỄN HỮU PHƯỚC",
        "description": "Số 04/01, ấp Phú Tâm, xã An Phú, huyện Tịnh Biên, An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [104.9722964,10.640435]
      },
      "properties": {
        "title": "VINH LIÊN",
        "description": "Tổ 6, ấp Trung Bắc Hưng, xã Nhơn Hưng, huyện Tịnh Biên, An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [104.9390342,10.3530043]
      },
      "properties": {
        "title": "MINH PHÚ",
        "description": "ấp Phú Lâm, xã Lương An Trà, huyện Tri Tôn, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.0729531,10.3271923]
      },
      "properties": {
        "title": "PHƯƠNG HUY 1",
        "description": "Tỉnh lộ 943, khóm I, thị trấn Tri Tôn, huyện Tri Tôn, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.051784,10.317995]
      },
      "properties": {
        "title": "THANH VÂN",
        "description": "ấp Tân Lợi, xã Tân Tuyến, Tri Tôn, An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.102304,10.693797]
      },
      "properties": {
        "title": "KIM ĐIỀN (CHÂU ĐỐC)",
        "description": "Thành phố Châu Đốc, An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.0286707,10.656689]
      },
      "properties": {
        "title": "VÕ THỊ TÚ TRINH",
        "description": "Tổ 06, ấp Cây Châm, xã Vĩnh Tế, thành phố Châu Đốc , An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.4267813,10.3942753]
      },
      "properties": {
        "title": "ÁNH GIANG",
        "description": "Số 60/33/6 Quán Cơ Thành, Phường Bình Khánh, Thành Phố Long Xuyên, Tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.4379578,10.366357]
      },
      "properties": {
        "title": "NGUYỄN NHƯ",
        "description": "40M5 Đông Thịnh 9, Mỹ Phước, TP. Long Xuyên, tỉnh An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [105.3743533,10.3829718]
      },
      "properties": {
        "title": "TẤN PHÁT",
        "description": "Tổ 17, ấp Bình Hòa, Xã Mỹ khánh, TP Long Xuyên, An Giang",
        "marker-color": "#0000FF",
        "marker-size": "small",
        "marker-symbol": "2"
      }
    }